name: basic exmaple

on:
 push:
  branches:
   - main
   
 jobs:
   build:
   runs-on: ubuntu-latest

 steps:
    - name: checking
      uses: actions/checkout@v4

    - name: compile java
        uses:javac DemoName.java

    - name: run java
      uses: DemoName.java
      
    
    
