name: basic example

on:
 push:
  branches:
    - main

jobs:
 build:
  runs-on: ubuntu-latest
 
  steps:
   - name: checkout
     uses: actions/checkout@v3

   - name: setup java
     uses: actions/setup-java@v3

   - name: Compile Java
     run: javac DemoName.java

   - name: Run java
     run: java DemoName
