name: Java Hello World

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin

    - name: Compile DemoName.java
      run: javac DemoName.java

    - name: Run HelloWorld
      run: java DemoName
