permissions: read-all

name: hello world

on: push

jobs:
 build:
  runs-on: ubuntu-latest
  permissions: write-all

  steps:
     - uses: actions/chekout@v3
  
     - uses: actions/setup-java@v4
       with:
         java-version: 17
         distribution: temurin

     - name: Compile java
       run: javac DemoName.java

     - name: Run java
       run: java DemoName

     
     
     
